export default {
  generatesecretKey: 'FouadTest',
  secretKey: 'FouadTest',
  privateKey:
    '-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAmiqGnu0RgoiFPquVEsvFOTWKBxfQBAdQJK8y1Tmg8fs6IoRK\nVmSz9qRi13qhr8WkrLNG7p3PAq8Qj3o17BcxTDBSzYagvkSEIw1QSBIg045dNoLK\n7R3iQtnmG5Ogp4ADtNSWJlQbZE6SDfCZOg7l8+e1dpILegaQQtrjBwQmmTZYd+7/\n0SIbhPRb0qh20qj3v7qAKAf7RWuwVqddJg5ePypUc42I31qQM44JcJ/EY6hIHI1b\nZePMFpI91U09nk0x3A+REMLHEKuxAbQMZwk2NyDBaatXsLkNYMhdQSJihAjdxXEt\n5+iacIeu4vLw+apuF0AoAWDgYxDGsc+/rGAW+QIDAQABAoIBAAGk8HijeKtWv20S\nsW1Y5QqeKpG2zE4usckiYT1q9u99yXnyxUQ0oMLBsBgyQ6U3S3FYHCqRXlLeASQ2\nnnqdKLZyUX/FrtM4sdwZ2UBbiSQYgaACNx3eUrp5zn1+zpjawa9dERjpjr08JUym\nw0ueOw+l6gaQujSb+0/rO76oaaz6pih3EYfABYCa4QXFdhcef5vgpS3BDf/0La2K\nXHu1kcgt/At6buckKMtwZhYigEwB+i6pJCOVA7noKEcdHuYe9FqjnMlebAP53rph\nfhNnM14NeEVG5LgCw0zOvwYMmE7lNDwUuW8GPn18EzENrOycWOrJ3GJ8rIsmNrlA\nJOUxaQ0CgYEA12/Ey9bjPVWVW3xCc46ZrTRR+yp98MMzlv8T748H/h5Am8ZQIte3\nQwiLkWlS8eyawYX/Mi3DTdqIBdwBVN+Ptimf4PTcRhPcVF0Wet7BnAqLAw0AxDLB\ntmBuD4PDdZUc1jxmyF4EiOlDW1tjUD3dLJ1iLnjBYAmsjlyRppZTCvsCgYEAtzF3\nexgTMXUuy1xyg/gIbqoUQ6djT1uy7GXYRaTsMVeRYD52BpkC6bLQGhOJdZ7fT2s4\niOiY31D1RoYm6h8dQ3H9odUj5BeWVlM64iSP1ccyX/cokDsicSlau1HWMCQ0fzDK\n2VyYb2JvqS6dL9PfvZSvCGwI93DraIGbEaNOg5sCgYAZOfM3UzBErFLS5Zf6ZAZG\nq8u1t2IL4S+XTMMO2Ba9gNlb5DrZ+Zxx8vw0yLp3rZbpdkFNpOIrqZ0n4n0dbRgs\n4m7gLovkgMrZ7hSFyrOtC+b/MnSWhML+EgiRNIKcsBsyUtxONgQd7AKBHhBhAv11\nDfDDNEygbEGSYfCEKzIKJQKBgH1Be1pU6bqlTuuJOFt3Wfygmd5wMvzty/bK5Acq\nbryGDUZrLrPwJwe3VYae2RvtFu7sdulVcEEwz6P60dy+jXmyFSNz4mhwoEBCBD7f\nlOEspArtqXSEmlYZWoo9uF+OQb69k9Tu9OMjwQlCcANlsNOlN9BgXfkh4jPAelCj\nAmoFAoGBANTyci7IByewySEC0M7adzNmiDVxKGirm0OT3nbQlHK7hvEvgQwK6dMZ\nITC2tLL8j47cIDtnsQl4Q66uwzezTEblChSOvQaJWizR4Vcsle1s17w8c4PBBDv8\nxZKviOspLaMpR6FLj+g5bJs9luobk5L6zPGz86y268cNJ6kPYqPw\n-----END RSA PRIVATE KEY-----',
  host: 'http://localhost',
  port: '21465',
  deviceName: 'SmartSchoolDevice',
  poweredBy: 'SmartSchool-Server',
  startAllSession: false,
  customUserDataDir: './userDataDir/',
  tokenStoreType: 'mongodb',
  maxListeners: 250,
  webhook: {
    url: null,
    autoDownload: false,
    uploadS3: false,
    readMessage: false,
    allUnreadOnStart: false,
    listenAcks: false,
    onPresenceChanged: false,
    onParticipantsChanged: false,
    onReactionMessage: false,
    onPollResponse: false,
    onRevokedMessage: false,
    onLabelUpdated: false,
    onSelfMessage: false,
    listenMessages: false,
    ignore: ['status@broadcast'],
  },
  websocket: {
    autoDownload: false,
    uploadS3: false,
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true,
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45,
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action
    logger: ['console', 'file'],
  },
  createOptions: {
    headless: true,
    autoClose: 120000,
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',

      '--disable-features=LeakyPeeker',

      '--unlimited-storage',
      '--full-memory-crash-report',
      '--force-gpu-mem-available-mb',
      '--js-flags=--expose-gc',
      '--no-default-browser-check',
      '--disable-site-isolation-trials',
      '--no-experiments',
      '--disable-webgl',
      '--disable-infobars',
      '--window-position=0,0',
      '--ignore-certifcate-errors',
      '--ignore-certifcate-espki-list',
      '--disable-threaded-animation',
      '--disable-threaded-scrolling',
      '--disable-in-process-stack-traces',
      '--disable-histogram-customizer',
      '--disable-gl-extensions',
      '--disable-composited-antialiasing',
      '--disable-canvas-aa',
      '--disable-3d-apis',
      '--disable-accelerated-2d-canvas',
      '--disable-accelerated-jpeg-decoding',
      '--disable-accelerated-mjpeg-decode',
      '--disable-app-list-dismiss-on-blur',
      '--disable-accelerated-video-decode',
      '--disable-dev-shm-usage',
      '--ignore-gpu-blacklist',
      '--disable-gpu',
      '--disable-setuid-sandbox',
      '--log-level=1',
      '--no-treekill',
      '--enable-features=NetworkService',
    ],
    /**
     * Example of configuring the linkPreview generator
     * If you set this to 'null', it will use global servers; however, you have the option to define your own server
     * Clone the repository https://github.com/wppconnect-team/wa-js-api-server and host it on your server with ssl
     *
     * Configure the attribute as follows:
     * linkPreviewApiServers: [ 'https://www.yourserver.com/wa-js-api-server' ]
     */
    linkPreviewApiServers: null,
  },
  mapper: {
    enable: false,
    prefix: 'tagone-',
  },
  db: {
    maxPoolSize: 5000,
    mongodbDatabase: 'tokens',
    mongodbCollection: '',
    mongodbUser: '',
    mongodbPassword: '',
    mongodbHost: '127.0.0.1',
    mongoIsRemote: false,
    mongoURLRemote: '',
    mongodbPort: 27017,
    redisHost: 'localhost',
    redisPort: 6379,
    redisPassword: '',
    redisDb: 0,
    redisPrefix: 'docker',
  },
  aws_s3: {
    region: 'sa-east-1',
    access_key_id: null,
    secret_key: null,
    defaultBucketName: null,
    endpoint: null,
    forcePathStyle: null,
  },
};
